### PR TITLE
plasma theme and new colors

### PR DESCRIPTION
**Pull request by varlesh**
preview

### CODE REVIEW

**Comment by varlesh** [comment]
Available all Icons for plasma tray. Draw from source Numix Icon Theme (symbolic and panel). Somes modified for better looking, for example printer, klipper and etc...
Tested with Plasma 5.8 (maybe work on KDE4 - need test). Recommend use with Breeze style and new Numix Colors.

**Comment by varlesh** [comment]
More screens.
Volume Widget:
image
Playbar Widget:
image
Network Monitor Widget:
image

**Comment by varlesh** [comment]
Colors (with Breeze engine):
image

**Comment by khurshid-alam** [comment]
@varlesh Thanks. We will look into this. Couple of points:

1. Numix recently changed color scheme. But you are still using old color scheme...any specific reason for that?

2. DecorationFocus/DecorationHover = 214,73,55! ?

3. If I am not this will break the theme with older plasma desktop (KDE 4.x)?

**Comment by varlesh** [comment]
@khurshid-alam fixed
image

**Comment by varlesh** [comment]
> Numix recently changed color scheme. But you are still using old color scheme...any specific reason for that?

Yes, i'm found scrren old version and create. LOL :) But now fixed with new colors

> DecorationFocus/DecorationHover = 214,73,55! ?

Yes, now fixed #f0544c

> If I am right, this will break the theme with older plasma desktop (KDE 4.x)?

Theme should work on KDE 4, but i'm not tested. I'm have only Plasma 5.8

**Comment by varlesh** [comment]
Now replace colors:
Hilight d64937 > f0544c
Base color 2d2d2d > 444444

And some fixes color-scheme, icons, buttons and etc...

**Comment by satya164** [comment]
@varlesh also need to replace background color to be `#eee` and base color (the list and grid background) to be `#fff`

**Comment by satya164** [comment]
Here is the color scheme https://github.com/numixproject/numix-gtk-theme/blob/master/src/gtk-3.0/scss/_global.scss#L5

**Comment by varlesh** [comment]
done

**Comment by varlesh** [comment]
image

**Comment by khurshid-alam** [comment]
@satya164 This is definitely breaking KDE 4.x (qtcurve styles etc)...at-least in some areas.  The question is should we drop support for KDE 4.x? I don't think any distro ships KDE 4.x other than Debian. May be I should bump the version.

**Comment by satya164** [comment]
@khurshid-alam I don't mind dropping support for KDE 4.x

@varlesh Can we make the buttons look closer to the GTK theme? @khurshid-alam maybe you can share screenshot of widget factory?

Here's a mockup I had, but probably not accurate

image

**Comment by varlesh** [comment]
QtCurve very old style and not good look with Plasma 5. Better use style with Breeze. I don't use KDE 4 and QtCurve anymore. And last version style created 3 years ago. I think KDE 4 version need discontinued and del QtCurve style.

**Comment by varlesh** [comment]
>  Can we make the buttons look closer to the GTK theme? @khurshid-alam maybe you can share screenshot of widget factory?

No. Buttons drawing Breeze style. But this maybe possible with [Kvantum](https://github.com/tsujan/Kvantum/tree/master/Kvantum) engine.

**Comment by varlesh** [comment]
@satya164 You will support this branch and update new version for Plasma or fix bugs?

**Comment by satya164** [comment]
Wow. So many engines!

> @satya164 You will support this branch and update new version for Plasma or fix bugs?

Not really. I don't use KDE (not even Linux anymore), so I won't be able to do it. Somebody who uses KDE actively should do it.

**Comment by varlesh** [comment]
Ok. If merged - i'm del my branch https://github.com/varlesh/numix-plasma and fork https://github.com/varlesh/numix-kde-theme  also del this topics:
https://store.kde.org/p/1160342/
https://store.kde.org/p/1160340/
Because this style will be Numix Project.

**Comment by varlesh** [comment]
Solve - merge or close.

**Comment by satya164** [comment]
cc @lots0logs

**Comment by khurshid-alam** [comment]
Thanks. I will merge this soon. On launchpad we are using this recipe https://code.launchpad.net/~numix/+recipe/numix-kde-theme and [debian-packaging](https://code.launchpad.net/~paolorotolo/numix-kde/numix-kde-theme-packaging) which needs to be updated

**Comment by varlesh** [comment]
Ok, i'm del my branch and topics

**Comment by varlesh** [comment]
Save AUTHORS and LICENSE

**Comment by varlesh** [comment]
@khurshid-alam Why not merged?

**Comment by khurshid-alam** [comment]
@varlesh Sorry. I forgot to ask.....Does everything goes under /usr/share/plasma/desktoptheme/Numix ? Or does some part needs to somewhere else? 

I did found many old widgets and apps broken(probably fault on their part)....I tested without deleteting qtcurve...(they can co-exist right?)

**Comment by khurshid-alam** [comment]
@varlesh And beside there is a discussion going on for merging different desktop sessions under a same repo. You can see the prototype here: https://github.com/Antergos/Numix-Frost.....I will come back to this issue later.

**Comment by varlesh** [comment]
@khurshid-alam 
> Does everything goes under /usr/share/plasma/desktoptheme/Numix ? Or does some part need to go somewhere else?

I don't understand what you mean. You tested plasma theme with KDE 5.8?
image
If you really not interested i'm close this PR!

**Comment by varlesh** [comment]
All fixed, all work - what you want?

**Comment by varlesh** [comment]
I'm create Plasma theme, fixed all colors, upload changes, show screenshots... 
What you don't like? You can show me "old widgets and apps broken"?

**Comment by varlesh** [comment]
@Foggalong Your members very amazing...

**Comment by khurshid-alam** [comment]
@varlesh I couldn't show you screenshot as I am away from the machine. Don't get frustrated. On launchpad, the debian package recipe that we are using was registered by @paolorotolo and I don't have upload right (https://code.launchpad.net/~paolorotolo/numix-kde/numix-kde-theme-packaging). I already pinged him few days ago....:(

About the theme, everything works for plasma >5.6, but no so much for qt4....Sean told me that both old and new style can co-exist......and that's what I am trying to find out......to proper way to do this.

Please reopen the pull. Thanks.

**Comment by varlesh** [comment]
@khurshid-alam I'm add only colorscheme and Plasma theme. Qt4/Qt5 apps use Breeze engine. New PR openned: https://github.com/numixproject/numix-kde-theme/pull/6

**Comment by khurshid-alam** [comment]
Thanks.

**Pull request closed without merging**
